export const AppointmentActionTypes = {
  //getDoctors
  PATIENT_GET_DOCTORS_REQUEST: 'PATIENT_GET_DOCTORS_REQUEST',
  PATIENT_GET_DOCTORS_SUCCESS: 'PATIENT_GET_DOCTORS_SUCCESS',
  PATIENT_GET_DOCTORS_FAILURE: 'PATIENT_GET_DOCTORS_FAILURE',

  //getDoctorsAvailability
  PATIENT_DOCTORS_AVAILABILITY_FAILURE: 'PATIENT_DOCTORS_AVAILABILITY_FAILURE',
  PATIENT_DOCTORS_AVAILABILITY_REQUEST: 'PATIENT_DOCTORS_AVAILABILITY_REQUEST',
  PATIENT_DOCTORS_AVAILABILITY_SUCCESS: 'PATIENT_DOCTORS_AVAILABILITY_SUCCESS',

  // getAllDoctorList
  PATIENT_GET_ALL_DOCTORS_REQUEST: 'PATIENT_GET_ALL_DOCTORS_REQUEST',
  PATIENT_GET_ALL_DOCTORS_SUCCESS: 'PATIENT_GET_ALL_DOCTORS_SUCCESS',
  PATIENT_GET_ALL_DOCTORS_FAILURE: 'PATIENT_GET_ALL_DOCTORS_FAILURE',

  //postBookAppointment
  PATIENT_APPOINTMENT_BOOKING_REQUEST: 'PATIENT_APPOINTMENT_BOOKING_REQUEST',
  PATIENT_APPOINTMENT_BOOKING_SUCCESS: 'PATIENT_APPOINTMENT_BOOKING_SUCCESS',
  PATIENT_APPOINTMENT_BOOKING_FAILURE: 'PATIENT_APPOINTMENT_BOOKING_FAILURE',

  // postCancelAppointment
  PATIENT_APPOINTMENT_CANCEL_REQUEST: 'PATIENT_APPOINTMENT_CANCEL_REQUEST',
  PATIENT_APPOINTMENT_CANCEL_SUCCESS: 'PATIENT_APPOINTMENT_CANCEL_SUCCESS',
  PATIENT_APPOINTMENT_CANCEL_FAILURE: 'PATIENT_APPOINTMENT_CANCEL_FAILURE',

  //postRecheduleAppointment
  PATIENT_APPOINTMENT_RECHEDULE_REQUEST: 'PATIENT_APPOINTMENT_RECHEDULE_REQUEST',
  PATIENT_APPOINTMENT_RECHEDULE_SUCCESS: 'PATIENT_APPOINTMENT_RECHEDULE_SUCCESS',
  PATIENT_APPOINTMENT_RECHEDULE_FAILURE: 'PATIENT_APPOINTMENT_RECHEDULE_FAILURE',

  //postAppointmentStatus
  PATIENT_APPOINTMENT_STATUS_REQUEST: 'PATIENT_APPOINTMENT_STATUS_REQUEST',
  PATIENT_APPOINTMENT_STATUS_SUCCESS: 'PATIENT_APPOINTMENT_STATUS_SUCCESS',
  PATIENT_APPOINTMENT_STATUS_FAILURE: 'PATIENT_APPOINTMENT_STATUS_FAILURE',

  // getAppointmentsByPatient
  PATIENT_APPOINTMENT_BY_PATIENT_REQUEST: 'PATIENT_APPOINTMENT_BY_PATIENT_REQUEST',
  PATIENT_APPOINTMENT_BY_PATIENT_SUCCESS: 'PATIENT_APPOINTMENT_BY_PATIENT_SUCCESS',
  PATIENT_APPOINTMENT_BY_PATIENT_FAILURE: 'PATIENT_APPOINTMENT_BY_PATIENT_FAILURE',

  //getVideoConferenceDetails
  PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT_REQUEST: 'PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT_REQUEST',
  PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT_SUCCESS: 'PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT_SUCCESS',
  PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT_FAILURE: 'PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT_FAILURE',
  DELETE_PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT: 'DELETE_PATIENT_VIDEO_CONFERENCE_DETAILS_PATIENT',

  //clear appointment details
  CLEAR_APPOINTMENT_DETAILS: 'CLEAR_APPOINTMENT_DETAILS'
}