export const MedicationTypes = {
  //getMedicationbyPatient
  GET_MEDICATION_BY_PATIENT_REQUEST: 'GET_MEDICATION_BY_PATIENT_REQUEST',
  GET_MEDICATION_BY_PATIENT_SUCCESS: 'GET_MEDICATION_BY_PATIENT_SUCCESS',
  GET_MEDICATION_BY_PATIENT_FAILURE: 'GET_MEDICATION_BY_PATIENT_FAILURE',

  // getMedicationsByAppointmentId
  GET_MEDICATION_BY_APPOINTMENT_REQUEST: 'GET_MEDICATION_BY_APPOINTMENT_REQUEST',
  GET_MEDICATION_BY_APPOINTMENT_SUCCESS: 'GET_MEDICATION_BY_APPOINTMENT_SUCCESS',
  GET_MEDICATION_BY_APPOINTMENT_FAILURE: 'GET_MEDICATION_BY_APPOINTMENT_FAILURE',
}