export const VitalTypes = {
  PATIENT_UPDATE_VITALS_REQUEST: 'PATIENT_UPDATE_VITALS_REQUEST',
  PATIENT_UPDATE_VITALS_SUCCESS: 'PATIENT_UPDATE_VITALS_SUCCESS',
  PATIENT_UPDATE_VITALS_FAILURE: 'PATIENT_UPDATE_VITALS_FAILURE',

  GET_VITALS_BY_PATIENT_REQUEST: 'GET_VITALS_BY_PATIENT_REQUEST',
  GET_VITALS_BY_PATIENT_SUCCESS: 'GET_VITALS_BY_PATIENT_SUCCESS',
  GET_VITALS_BY_PATIENT_FAILURE: 'GET_VITALS_BY_PATIENT_FAILURE',
}