export const CommonTypes = {
  GET_PAYMENTS_HISTORY_REQUEST: 'GET_PAYMENTS_HISTORY_REQUEST',
  GET_PAYMENTS_HISTORY_SUCCESS: 'GET_PAYMENTS_HISTORY_SUCCESS',
  GET_PAYMENTS_HISTORY_FAILURE: 'GET_PAYMENTS_HISTORY_FAILURE',

  GET_DOCTOR_DETAILS_REQUEST: 'GET_DOCTOR_DETAILS_REQUEST',
  GET_DOCTOR_DETAILS_SUCCESS: 'GET_DOCTOR_DETAILS_SUCCESS',
  GET_DOCTOR_DETAILS_FAILURE: 'GET_DOCTOR_DETAILS_FAILURE',

  UPDATE_DOCTOR_PROFILE_REQUEST: 'UPDATE_DOCTOR_PROFILE_REQUEST',
  UPDATE_DOCTOR_PROFILE_SUCCESS: 'UPDATE_DOCTOR_PROFILE_SUCCESS',
  UPDATE_DOCTOR_PROFILE_FAILURE: 'UPDATE_DOCTOR_PROFILE_FAILURE',

  START_NAVIGATION_LOADER: 'START_NAVIGATION_LOADER'


}