export const CommonTypes = {
  GET_PAYMENTS_HISTORY_REQUEST: 'GET_PAYMENTS_HISTORY_REQUEST',
  GET_PAYMENTS_HISTORY_SUCCESS: 'GET_PAYMENTS_HISTORY_SUCCESS',
  GET_PAYMENTS_HISTORY_FAILURE: 'GET_PAYMENTS_HISTORY_FAILURE',

  GET_DOCTOR_DETAILS_REQUEST: 'GET_DOCTOR_DETAILS_REQUEST',
  GET_DOCTOR_DETAILS_SUCCESS: 'GET_DOCTOR_DETAILS_SUCCESS',
  GET_DOCTOR_DETAILS_FAILURE: 'GET_DOCTOR_DETAILS_FAILURE',

  UPDATE_DOCTOR_PROFILE_REQUEST: 'UPDATE_DOCTOR_PROFILE_REQUEST',
  UPDATE_DOCTOR_PROFILE_SUCCESS: 'UPDATE_DOCTOR_PROFILE_SUCCESS',
  UPDATE_DOCTOR_PROFILE_FAILURE: 'UPDATE_DOCTOR_PROFILE_FAILURE',

  SEND_OTP_REQUEST: 'SEND_OTP_REQUEST',
  SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
  SEND_OTP_FAILURE: 'SEND_OTP_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  CLEAR_OTP_STATE: 'CLEAR_OTP_STATE',

  START_NAVIGATION_LOADER: 'START_NAVIGATION_LOADER'


}