export const medicalSpecializations = {
  undergraduate: ["MBBS (Bachelor of Medicine, Bachelor of Surgery)"],
  postgraduate: {
    MD: [
      "Anesthesiology",
      "Biochemistry",
      "Dermatology, Venereology, and Leprology",
      "Emergency Medicine",
      "Family Medicine",
      "General Medicine",
      "Microbiology",
      "Nuclear Medicine",
      "Obstetrics and Gynaecology",
      "Ophthalmology",
      "Orthopedics",
      "Otorhinolaryngology (ENT)",
      "Pathology",
      "Pediatrics",
      "Pharmacology",
      "Physical Medicine and Rehabilitation",
      "Psychiatry",
      "Radiodiagnosis",
      "Radiotherapy",
      "Social and Preventive Medicine/Community Medicine",
      "Tuberculosis and Respiratory Diseases",
    ],
    MS: [
      "General Surgery",
      "Ophthalmology",
      "Orthopedics",
      "Otorhinolaryngology (ENT)",
      "Anatomy",
      "Obstetrics and Gynaecology",
    ],
    DM: [
      "Cardiology",
      "Endocrinology",
      "Gastroenterology",
      "Nephrology",
      "Neurology",
      "Medical Oncology",
      "Clinical Hematology",
      "Rheumatology",
      "Cardiac Anesthesia",
      "Pediatric Cardiology",
      "Pediatric Gastroenterology",
      "Pediatric Nephrology",
      "Pediatric Neurology",
      "Neonatology",
      "Critical Care Medicine",
      "Hepatology",
      "Infectious Diseases",
      "Medical Genetics",
      "Neonatology",
      "Clinical Immunology",
      "Interventional Radiology",
      "Neuro-Radiology",
      "Cardiac Radiology",
      "Pediatric Radiology",
      "Reproductive Medicine and Surgery",
    ],
    MCh: [
      "Cardio Thoracic and Vascular Surgery (CTVS)",
      "Neuro Surgery",
      "Pediatric Surgery",
      "Plastic and Reconstructive Surgery",
      "Urology",
    ],
    DNB: [
      "Cardiology",
      "Gastroenterology",
      "Neurology",
      "Medical Oncology",
      "Pediatric Cardiology",
      "Pediatric Gastroenterology",
      "Pediatric Nephrology",
      "Pediatric Neurology",
      "Neonatology",
      "Cardiac Anesthesia",
      "Critical Care Medicine",
      "Hepatology",
      "Infectious Diseases",
      "Reproductive Medicine and Surgery",
      "Surgical Oncology",
      "Urology",
    ],
  },
  diploma: [
    "Diploma in Anesthesia",
    "Diploma in Child Health (DCH)",
    "Diploma in Dermatology, Venereology, and Leprosy (DDVL)",
    "Diploma in Obstetrics and Gynaecology (DGO)",
    "Diploma in Ophthalmology (DO)",
    "Diploma in Orthopaedics (D Ortho)",
    "Diploma in Otorhinolaryngology (DLO)",
    "Diploma in Psychological Medicine (DPM)",
    "Diploma in Public Health (DPH)",
    "Diploma in Tuberculosis and Chest Diseases (DTCD)",
    // Add more diploma specializations as needed
  ],
  research: ["Ph.D. (Doctor of Philosophy)"],
};