export const AppointmentActionTypes = {
  // getAppointmentsByPatient
  DOCTOR_UPCOMMING_APPOINTMENT_REQUEST: 'DOCTOR_UPCOMMING_APPOINTMENT_REQUEST',
  DOCTOR_UPCOMMING_APPOINTMENT_SUCCESS: 'DOCTOR_UPCOMMING_APPOINTMENT_SUCCESS',
  DOCTOR_UPCOMMING_APPOINTMENT_FAILURE: 'DOCTOR_UPCOMMING_APPOINTMENT_FAILURE',

  DOCTOR_COMPELTE_APPOINTMENT_REQUEST: 'DOCTOR_COMPELTE_APPOINTMENT_REQUEST',
  DOCTOR_COMPELTE_APPOINTMENT_SUCCESS: 'DOCTOR_COMPELTE_APPOINTMENT_SUCCESS',
  DOCTOR_COMPELTE_APPOINTMENT_FAILURE: 'DOCTOR_COMPELTE_APPOINTMENT_FAILURE',

  // getAppointmentsByPatient
  DOCTOR_ADD_MEDICATION_REQUEST: 'DOCTOR_ADD_MEDICATION_REQUEST',
  DOCTOR_ADD_MEDICATION_SUCCESS: 'DOCTOR_ADD_MEDICATION_SUCCESS',
  DOCTOR_ADD_MEDICATION_FAILURE: 'DOCTOR_ADD_MEDICATION_FAILURE',


  CLEAR_STATE: 'CLEAR_STATE'

}