export const ProfileActionTypes = {
  // getAppointmentsByPatient
  DOCTOR_CREATE_AVAILABILITY_REQUEST: 'DOCTOR_CREATE_AVAILABILITY_REQUEST',
  DOCTOR_CREATE_AVAILABILITY_SUCCESS: 'DOCTOR_CREATE_AVAILABILITY_SUCCESS',
  DOCTOR_CREATE_AVAILABILITY_FAILURE: 'DOCTOR_CREATE_AVAILABILITY_FAILURE',

}