export const API: any = {
  loginAPI: '/api/auth/patient/signin',
  loginDoctorAPI: '/api/auth/doctor/signin',
  patient_registration: '/api/auth/patient/signup',
  helathcare_registration_API: '/api/auth/doctor/signup',
  updatePatientProfile: '/api/auth/updatePatientProfile',
  doctor_search: '/api/doctor/search',
  getDoctorsAvailability: '/api/doctor/getDoctorsAvailability',
  bookAppointment: '/api/doctor/bookappointment',
  cancelAppointment: '/api/doctor/cancelAppointment',
  recheduleAppointment: '/api/doctor/recheduleAppointment',
  getAppointmentStatusByID: '/api/doctor/getAppointmentStatusByID',
  getAppointmentByPatient: '/api/doctor/getAppointmentByPatient',
  getVideoConferenceDetails: '/api/doctor/getVideoConferenceDetails',
  getMyUpcommingAppointments: '/api/doctor/getMyUpcommingAppointments',
  addMedication: '/api/doctor/addMedication',
  createAvailability: '/api/doctor/createAvailability',
  getMedicationbyPatient: '/api/patient/getMedicationbyPatient',
  updateVitals: '/api/patient/updateVitals',
  getAllVitalsByPatient: '/api/patient/getAllVitalsByPatient',
  getMedicationsByAppointmentId: '/api/patient/getMedicationsByAppointmentId',
  getAllDoctorList: '/api/doctor/getAllDoctorList',
  fetchDoctorDetails: '/api/doctor/fetchDoctorDetails',
  refreshToken: '/api/auth/refreshToken',
  getPaymentHistory: '/api/payment/fetchPaymentHistory',
  sendOTP: '/api/forgotPasssword/sendOtp',
  forgotPassword: '/api/auth/forgotPassword',
  completeAppointment: '/api/doctor/completeAppointment'

}